version: 2.17
jobs:
  build:
    working_directory: ~/repo
    docker:
      — image: circleci/node:12-stretch-browsers-legacy
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules