version: 2.17

# Define the jobs we want to run for this project
jobs:
    build:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: install-npm
                command: npm install
    test:
        docker:
            - image: circleci/<language>:<version TAG>
        steps:
            - checkout
            - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
    build_and_test:
        jobs:
        - build
        - test